[package]
name = "dnsec"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.6"
log = "0.4.25"
reqwest = "0.12.12"
serde = "1.0.217"
tokio = "1.43.0"
toml = "0.8.20"
trust-dns = "0.23.2"
trust-dns-proto = "0.23.2"
